### ISSUE TITLE
agent path error?

### ISSUE THREAD

**Issue by mgaulton** [tomas/rtop#2]
I'm loving the idea this project has but I can't seem to get it to run

ssh_config has this at the very bottom
Host IP IP2 IP3
   ForwardAgent yes

But i'm getting the below
`
Error: You must set a valid agent path to allow agent forwarding
    at Client.connect (/usr/local/lib/node_modules/rtop/node_modules/ssh2/lib/client.js:133:11)
    at Remote.connect (/usr/local/lib/node_modules/rtop/lib/remote.js:62:7)
    at Remote.start (/usr/local/lib/node_modules/rtop/lib/remote.js:99:8)
    at /usr/local/lib/node_modules/rtop/lib/rtop.js:529:16
    at Array.forEach (native)
    at Object.Rtop.init [as start] (/usr/local/lib/node_modules/rtop/lib/rtop.js:526:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/rtop/bin/rtop:21:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
`

**Comment by tomas** [comment]
Are you actually running an SSH agent? What output do you get when running `ssh-add -l`?

**Comment by mgaulton** [comment]
Seems my agent had errors.
setting the agent to start auto
ssh-add the keys.
working (tho my busybox nas doens't seem to have the required tools.

Sorry for the trouble.
