### ISSUE TITLE
not a terminal 

### ISSUE THREAD

**Issue by zewolfen** [tomas/rtop#3]
i am trying to use rtop api but i am getting not a terminal error, can some one help ?

`const express = require('express')
const app = express()
var rtop  = require('rtop');

app.get('/health',function(req,res){

var hosts =  ["10.80.0.63:22"]
    opts  =  { key_path: '/home/hastest/server/hastest.pem' };

rtop.start(hosts, opts);
})

app.listen(process.env.PORT || 3000)
console.log('server started on 3000');`

**Comment by tomas** [comment]
Can you show the full stacktrace?

**Comment by zewolfen** [comment]
@tomas do you mean this  ? 



Error: Not a terminal.
    at Program.listen (/home/hastest/server/node_modules/rtop/node_modules/blessed/lib/program.js:260:11)
    at new Program (/home/hastest/server/node_modules/rtop/node_modules/blessed/lib/program.js:108:8)
    at Program (/home/hastest/server/node_modules/rtop/node_modules/blessed/lib/program.js:30:12)
    at new Screen (/home/hastest/server/node_modules/rtop/node_modules/blessed/lib/widget.js:257:20)
    at Function.Screen (/home/hastest/server/node_modules/rtop/node_modules/blessed/lib/widget.js:246:12)
    at Object.init [as start] (/home/hastest/server/node_modules/rtop/lib/rtop.js:515:25)
    at /home/hastest/server/api.js:15:6
    at Layer.handle [as handle_request] (/home/hastest/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/hastest/server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/hastest/server/node_modules/express/lib/router/route.js:112:3)

I checked the rtop code  and i found not a terminal error is something related to the key i am not sure of that, ....... appreciate your help
