### ISSUE TITLE
Error: You must set a valid agent path to allow agent forwarding

### ISSUE THREAD

**Issue by devilsoulblack** [tomas/rtop#5]
Hola, me da el siguiente msg:

aandaluz@Mega-Nagios:/tmp$ rtop -u root -p 22 nna.mega.cl
Error: You must set a valid agent path to allow agent forwarding
    at Client.connect (/usr/local/lib/node_modules/rtop/node_modules/ssh2/lib/client.js:133:11)
    at Remote.connect (/usr/local/lib/node_modules/rtop/lib/remote.js:75:7)
    at Remote.start (/usr/local/lib/node_modules/rtop/lib/remote.js:102:8)
    at /usr/local/lib/node_modules/rtop/lib/rtop.js:530:16
    at Array.forEach (native)
    at Object.Rtop.init [as start] (/usr/local/lib/node_modules/rtop/lib/rtop.js:527:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/rtop/bin/rtop:21:8)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
aandaluz@Mega-Nagios:/tmp$

Adicional cuando ejecuto lo siguiente me da esto:

aandaluz@Mega-Nagios:/tmp$ ssh-add -l
Could not open a connection to your authentication agent.
aandaluz@Mega-Nagios:/tmp$

**Comment by tomas** [comment]
Pareciera que no estás corriendo un agente SSH en tu PC. Si haces `ps aux | grep ssh-agent` aparece algo? Si no, deberías correr algo como `eval $(ssh-agent)`.

**Comment by devilsoulblack** [comment]
@tomas este es el resultado:

aandaluz@Mega-Nagios:/tmp$ ps aux | grep ssh
root      2964  0.0  0.0  65512  6084 ?        Ss   16:16   0:00 /usr/sbin/sshd -D
aandaluz  4458  0.0  0.0  14132   980 pts/0    S+   17:04   0:00 grep --color=auto ssh
root     41061  0.0  0.0  92832  6756 ?        Ss   16:18   0:00 sshd: aandaluz [priv]
aandaluz 44575  0.0  0.0  92832  3416 ?        S    16:18   0:00 sshd: aandaluz@pts/0
aandaluz@Mega-Nagios:/tmp$ ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-wSLsnIBNGyYK/agent.13493; export SSH_AUTH_SOCK;
SSH_AGENT_PID=13513; export SSH_AGENT_PID;
echo Agent pid 13513;
aandaluz@Mega-Nagios:/tmp$

**Comment by tomas** [comment]
Ahí está pues, no estaba corriendo. Mata la instancia de ssh-agent que tengas corriendo con un `killall ssh-agent` y luego corre `eval $(ssh-agent)`. Después de eso `ssh-add -l` y vuelve a ejecutar `rtop`.
